spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: H2Pool
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console #http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true